-- MySQL Script generated by MySQL Workbench
-- 09/08/15 19:14:31
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usage_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usage_table` (
  `Srv.id` INT NULL AUTO_INCREMENT COMMENT '',
  `Servername` VARCHAR(45) NOT NULL COMMENT '',
  `Cpu_usage` FLOAT NULL COMMENT '',
  `Input_traffic` FLOAT NULL COMMENT '',
  `Output_traffic` FLOAT NULL COMMENT '',
  `Timestamp` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`Srv.id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rule_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rule_table` (
  `Rule.id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `SwitchPort` VARCHAR(45) NOT NULL COMMENT '',
  `MAC_src` VARCHAR(45) NULL COMMENT '',
  `MAC_dst` VARCHAR(45) NULL COMMENT '',
  `IP_src` VARCHAR(45) NULL COMMENT '',
  `IP_dst` VARCHAR(45) NULL COMMENT '',
  `S_port` VARCHAR(45) NULL COMMENT '',
  `D_port` VARCHAR(45) NULL COMMENT '',
  `Flow_table_Flow.id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Rule.id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Stats_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Stats_table` (
  `Stats.id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Packet_counter` FLOAT NULL COMMENT '',
  `Byte_counter` FLOAT NULL COMMENT '',
  `Flow_table_Flow.id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Stats.id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Flow_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Flow_table` (
  `Flow.id` INT NOT NULL COMMENT '',
  `Action` VARCHAR(45) NULL COMMENT '',
  `Rule_table_Rule.id` INT NOT NULL COMMENT '',
  `Stats_table_Stats.id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Flow.id`)  COMMENT '',
  INDEX `fk_Flow_table_Rule_table_idx` (`Rule_table_Rule.id` ASC)  COMMENT '',
  INDEX `fk_Flow_table_Stats_table1_idx` (`Stats_table_Stats.id` ASC)  COMMENT '',
  CONSTRAINT `fk_Flow_table_Rule_table`
    FOREIGN KEY (`Rule_table_Rule.id`)
    REFERENCES `mydb`.`Rule_table` (`Rule.id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Flow_table_Stats_table1`
    FOREIGN KEY (`Stats_table_Stats.id`)
    REFERENCES `mydb`.`Stats_table` (`Stats.id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Flow_table_has_Stats_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Flow_table_has_Stats_table` (
  `Flow_table_Flow.id` INT NOT NULL COMMENT '',
  `Stats_table_Stats.id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Flow_table_Flow.id`, `Stats_table_Stats.id`)  COMMENT '',
  INDEX `fk_Flow_table_has_Stats_table_Stats_table1_idx` (`Stats_table_Stats.id` ASC)  COMMENT '',
  INDEX `fk_Flow_table_has_Stats_table_Flow_table1_idx` (`Flow_table_Flow.id` ASC)  COMMENT '',
  CONSTRAINT `fk_Flow_table_has_Stats_table_Flow_table1`
    FOREIGN KEY (`Flow_table_Flow.id`)
    REFERENCES `mydb`.`Flow_table` (`Flow.id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Flow_table_has_Stats_table_Stats_table1`
    FOREIGN KEY (`Stats_table_Stats.id`)
    REFERENCES `mydb`.`Stats_table` (`Stats.id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Temporary_Flow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Temporary_Flow` (
  `Flow.id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `SwitchPort` VARCHAR(45) NOT NULL COMMENT '',
  `MAC_src` VARCHAR(45) NULL COMMENT '',
  `MAC_dst` VARCHAR(45) NULL COMMENT '',
  `IP_src` VARCHAR(45) NULL COMMENT '',
  `IP_dst` VARCHAR(45) NULL COMMENT '',
  `S_port` VARCHAR(45) NULL COMMENT '',
  `D_port` VARCHAR(45) NULL COMMENT '',
  `Action` VARCHAR(45) NULL COMMENT '',
  `Tomeout_time` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`Flow.id`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
